package org.example;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class lowesInterview {
    public static void main(String[] args) {
        List<List<String>> test = new ArrayList<>();
        List<String> test1 = new ArrayList<>();
        test1.add("A");
        test1.add("B");
        test.add(test1);
        List<String> list= test.stream().flatMap(L)

////        Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
////
////        Input : abc
////
////        Output : a, b, c, ab, bc, ac, abc //a ab ac abc b , bc , c
////  //abc
////ab
////ac
////a
////bc
////b
////c
////        Input : aaa
////
////        Output : a, a, a, aa, aa, aa, aaa
//        String inputs="abc";
//        String curr="";
//        List<String> res= new ArrayList<>();
//        generateSubsequence(inputs,curr,res);
//        for(String s: res){
//            System.out.println(s);
//        }
//
//
//    }
    }
}
